name: 'finding technical debt'
description: 'automatically detect flaws within source code'
inputs:
  number-issues:  # id of input
    description: 'selection of issues'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'