on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - name: Hello world action step
        id: hello
        uses: mmock-uni/td_action@v3.2.18